In [3]:
import numpy as np

In [20]:
# batch, frames, features
a = np.random.rand(5,108,500)
# print(a[0][0][1]) #첫번째 비디오의 첫번째 프레임의 두번째 피쳐값
print(len(a[0]))

108

In [21]:
import pandas as pd

In [33]:
# df = pd.read_csv("./dataset.csv")
df = pd.read_csv("./dataset.csv", index_col=-1)

In [34]:
df

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,x497,y497,x498,y498,x499,y499,x500,y500,x501,y501
class,,,,,,,,,,,,,,,,,,,,,
Face,0.515594,0.301150,0.514257,0.271725,0.515178,0.282907,0.511497,0.243691,0.514164,0.262101,...,0.462559,1.593878,0.580052,1.587713,0.459478,1.642439,0.588039,1.678396,0.479574,1.704145
Face,0.515986,0.301387,0.514780,0.270768,0.515641,0.282406,0.511627,0.242878,0.514632,0.261118,...,0.460195,1.580188,0.608734,1.619945,0.467298,1.631175,0.608260,1.679647,0.462179,1.705625
Face,0.515127,0.302423,0.513929,0.272160,0.514857,0.283248,0.511013,0.243773,0.513811,0.262532,...,0.469848,1.582703,0.610860,1.633027,0.473835,1.636785,0.610125,1.702946,0.462664,1.709355
Face,0.515285,0.301937,0.514177,0.271634,0.515011,0.282918,0.511076,0.243604,0.514042,0.262026,...,0.472045,1.610166,0.612320,1.657255,0.472823,1.656954,0.610811,1.729233,0.466499,1.722614
Face,0.515449,0.302624,0.514207,0.272319,0.515142,0.283526,0.511237,0.243925,0.514071,0.262652,...,0.471905,1.602265,0.612671,1.635861,0.474779,1.647826,0.611213,1.714411,0.466904,1.719442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Meet,0.482296,0.531612,0.482465,0.502657,0.482518,0.514993,0.479490,0.480530,0.482534,0.494329,...,0.434624,1.769399,0.559853,1.830921,0.436108,1.820519,0.529447,1.865133,0.433438,1.864522
Meet,0.482491,0.534621,0.482797,0.505501,0.482719,0.517639,0.479607,0.483438,0.482842,0.497272,...,0.430656,1.773449,0.561380,1.837587,0.434097,1.828325,0.527148,1.870741,0.422536,1.873791
Meet,0.482302,0.534373,0.482692,0.506140,0.482655,0.518216,0.479571,0.483840,0.482752,0.497820,...,0.428987,1.788002,0.559037,1.845699,0.430479,1.841323,0.528771,1.881279,0.425316,1.888610
Meet,0.482311,0.534325,0.482586,0.505820,0.482592,0.517875,0.479545,0.483352,0.482658,0.497484,...,0.429839,1.796842,0.557723,1.851370,0.430268,1.847411,0.532702,1.886046,0.429534,1.891785
Meet,0.482397,0.535366,0.482665,0.507156,0.482672,0.518881,0.479603,0.484642,0.482724,0.498868,...,0.439970,1.798727,0.568626,1.848943,0.440627,1.849139,0.541768,1.883886,0.441362,1.894536

In [49]:
a = df.loc["Meet"][0:4]
a

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,x497,y497,x498,y498,x499,y499,x500,y500,x501,y501
class,,,,,,,,,,,,,,,,,,,,,
Meet,0.521667,0.462772,0.520322,0.430003,0.520743,0.441088,0.514929,0.399291,0.519967,0.419824,...,0.435063,2.003716,0.590820,2.047714,0.430062,2.059688,0.576468,2.122723,0.458842,2.132117
Meet,0.523218,0.465283,0.522095,0.431733,0.522285,0.442559,0.516460,0.401242,0.521744,0.421714,...,0.443135,2.006516,0.606667,2.067767,0.440184,2.064059,0.588145,2.126850,0.460299,2.135304
Meet,0.523667,0.467692,0.522598,0.433789,0.522765,0.444594,0.516920,0.403158,0.522259,0.423742,...,0.439942,2.022046,0.612501,2.073921,0.438808,2.077321,0.596515,2.137420,0.450345,2.154485
Meet,0.523812,0.467671,0.522865,0.434629,0.522934,0.445047,0.517232,0.404040,0.522587,0.424672,...,0.454105,2.014493,0.611146,2.066360,0.451357,2.072545,0.606527,2.137679,0.471762,2.150020

In [51]:
print(a.iloc[2])

x1      0.523667
y1      0.467692
x2      0.522598
y2      0.433789
x3      0.522765
          ...
y499    2.077321
x500    0.596515
y500    2.137420
x501    0.450345
y501    2.154485
Name: Meet, Length: 1002, dtype: float64

In [59]:
ex = np.linspace(0,100,10) #0부터 100까지 10개 균일한 간격의 수 생성
ex

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])